### ISSUE TITLE
How to modify the format of my dataset

### ISSUE THREAD

**Issue by EmberaThomas** [shicaiwei123/patch_based_cnn#5]
Hello, now I want to use my own dataset for training, how should I modify the format

**Comment by showbit01** [comment]
> 

are you still working in this?

**Comment by shicaiwei123** [comment]
No， I'm working on the multimodal learning now



At 2022-06-03 15:31:53, "Shobhit Sharma" ***@***.***> wrote:

are you still working in this?

**Comment by showbit01** [comment]
> No， I'm working on the multimodal learning now
> 
> 
> 
> At 2022-06-03 15:31:53, "Shobhit Sharma" ***@***.***> wrote:
> 
> are you still working in this?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Cool

**Comment by showbit01** [comment]
> > No， I'm working on the multimodal learning now
> > 
> > 
> > 
> > At 2022-06-03 15:31:53, "Shobhit Sharma" ***@***.***> wrote:
> > 
> > are you still working in this?
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> 
> Cool
I am wondering how some product based company delivers reliable solution for face antispoofing from single image selfie...

**Comment by shicaiwei123** [comment]
As far as i know，one is very very very big dataaet（Tens of millions)，another is extra lighting.





电子科技大学 信息与通信工程院
School of Information and Communication Engineering 
University of Electronic Science and Technology of China (UESTC)
+18285516726
韦仕才






---- Replied Message ----
| From | Shobhit ***@***.***> |
| Date | 06/10/2022 14:50 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |

No， I'm working on the multimodal learning now

At 2022-06-03 15:31:53, "Shobhit Sharma" @.***> wrote:

are you still working in this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: @.***>

Cool
I am wondering how some product based company delivers reliable solution for face antispoofing from single image selfie...

**Comment by showbit01** [comment]
> As far as i know，one is very very very big dataaet（Tens of millions)，another is extra lighting.
> 
> 
> 
> 
> 
> 电子科技大学 信息与通信工程院
> School of Information and Communication Engineering 
> University of Electronic Science and Technology of China (UESTC)
> +18285516726
> 韦仕才
> 
> 
> 
> 
> 
> 
> ---- Replied Message ----
> | From | Shobhit ***@***.***> |
> | Date | 06/10/2022 14:50 |
> | To | ***@***.***> |
> | Cc | ***@***.******@***.***> |
> | Subject | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |
> 
> No， I'm working on the multimodal learning now
> 
> At 2022-06-03 15:31:53, "Shobhit Sharma" @.***> wrote:
> 
> are you still working in this?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: @.***>
> 
> Cool
> I am wondering how some product based company delivers reliable solution for face antispoofing from single image selfie...
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

That is what the main issue,if the model trained on one domain saved and tested and for unseen domains  learn by  capturing test images live with reinforcement learning..is it possible to do?

**Comment by shicaiwei123** [comment]
Sure，it not impossible. so the extra lighting can provide more robust feature and be used in current commercial app，such as Alipay



---- 回复的原邮件 ----
| 发件人 | Shobhit ***@***.***> |
| 日期 | 2022年06月10日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |

As far as i know，one is very very very big dataaet（Tens of millions)，another is extra lighting.

电子科技大学 信息与通信工程院
School of Information and Communication Engineering
University of Electronic Science and Technology of China (UESTC)
+18285516726
韦仕才

---- Replied Message ----
| From | Shobhit @.> |
| Date | 06/10/2022 14:50 |
| To | @.> |
| Cc | @.@.> |
| Subject | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |

No， I'm working on the multimodal learning now

At 2022-06-03 15:31:53, "Shobhit Sharma" @.***> wrote:

are you still working in this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: @.***>

Cool
I am wondering how some product based company delivers reliable solution for face antispoofing from single image selfie...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: @.***>

That is what the main issue,if the model trained on one domain saved and tested and for unseen domains learn by capturing test images live with reinforcement learning..is it possible to do?

**Comment by showbit01** [comment]
> Sure，it not impossible. so the extra lighting can provide more robust feature and be used in current commercial app，such as Alipay
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | Shobhit ***@***.***> |
> | 日期 | 2022年06月10日 16:05 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.******@***.***> |
> | 主题 | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |
> 
> As far as i know，one is very very very big dataaet（Tens of millions)，another is extra lighting.
> 
> 电子科技大学 信息与通信工程院
> School of Information and Communication Engineering
> University of Electronic Science and Technology of China (UESTC)
> +18285516726
> 韦仕才
> 
> ---- Replied Message ----
> | From | Shobhit @.> |
> | Date | 06/10/2022 14:50 |
> | To | @.> |
> | Cc | @.@.> |
> | Subject | Re: [shicaiwei123/patch_based_cnn] How to modify the format of my dataset (#5) |
> 
> No， I'm working on the multimodal learning now
> 
> At 2022-06-03 15:31:53, "Shobhit Sharma" @.***> wrote:
> 
> are you still working in this?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: @.***>
> 
> Cool
> I am wondering how some product based company delivers reliable solution for face antispoofing from single image selfie...
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: @.***>
> 
> That is what the main issue,if the model trained on one domain saved and tested and for unseen domains learn by capturing test images live with reinforcement learning..is it possible to do?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

Yeah will work on this then.Thanks..
