### ISSUE TITLE
深度图监督的困惑

### ISSUE THREAD

**Issue by csjgit123** [shicaiwei123/patch_based_cnn#8]
请问使用PRNet是生成训练集和验证集吗？测试集应该不需要深度图标签吧？

**Comment by shicaiwei123** [comment]
是的，测试集不需要标签。
理论上用prnet生成深度图，这里做了简化，真人深度图是全1像素值，欺骗是全0像素值






电子科技大学 信息与通信工程院
School of Information and Communication Engineering 
University of Electronic Science and Technology of China (UESTC)
+18285516726
韦仕才


发自 网易邮箱大师




---- Replied mail ----
| From | ***@***.***> |
| Date | 12/04/2021 09:22 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [shicaiwei123/patch_based_cnn] 深度图监督的困惑 (Issue #8) |

请问使用PRNet是生成训练集和验证集吗？测试集应该不需要深度图标签吧？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by csjgit123** [comment]
谢谢回复，我还有个疑问，如果我用PRNet生成的深度图作为标签就需要将下面else中的label改为深度图吗？
```
if img_path_split[-3] == 'spoofing' or img_path_split[-2]=='spoofing':
            label = np.float32(np.zeros((self.pixel_size, self.pixel_size)))
        else:
            label = np.float32(np.ones((self.pixel_size, self.pixel_size)))
```

**Comment by shicaiwei123** [comment]
是的，修改这里就行.





电子科技大学 信息与通信工程院
School of Information and Communication Engineering 
University of Electronic Science and Technology of China (UESTC)
+18285516726
韦仕才


发自 网易邮箱大师




---- Replied mail ----
| From | ***@***.***> |
| Date | 12/04/2021 12:05 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [shicaiwei123/patch_based_cnn] 深度图监督的困惑 (Issue #8) |

谢谢回复，我还有个疑问，如果我用PRNet生成的深度图作为标签就需要将下面else中的label改为深度图吗？

if img_path_split[-3] == 'spoofing' or img_path_split[-2]=='spoofing':

            label = np.float32(np.zeros((self.pixel_size, self.pixel_size)))

        else:

            label = np.float32(np.ones((self.pixel_size, self.pixel_size)))



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by csjgit123** [comment]
谢谢，解答了我很多困惑
